openapi: "3.0.0"
info:
  title: Generator service
  version: 1.0.0
  description: An api for service that generates exchange rates for currency pairs
components:
  schemas:
    ExchangeRate:
      type: object
      required:
        - time
        - rate
      properties:
        time:
          type: string
          format: date-time
        rate:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
paths:
  "/rates/{currency_pair}":
    get:
      summary: Returns rates for the currency pair
      description: Returns all exchange rates for the currency pair. Rates are order by the time of creation (from old to new)
      parameters:
        - in: path
          description: Currency pair
          name: currency_pair
          schema:
            type: string
      responses:
        "200":
          description: List of rates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeRate'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'