version: "3.9"

networks:
  service-network-1:
    name: ${SERVICE_NETWORK}
    external: true

services:
  analysis:
    image: analysis-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bin/:/root/
    env_file:
      - .env
    ports:
      - "8083:8080"
    networks:
      - service-network-1